on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    linter-execution:
        runs-on: ubuntu-latest
        steps:
          # Step 1.
          - name: Checkout code
            uses: actions/checkout@v4
    
          # Step 2.
          - name: Linter execution
            uses: github/super-linter@v4
            env: 
              DEFAULT_BRANCH: main
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              LINTER_RULES_PATH: /
              JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
              VALIDATE_JAVASCRIPT_ES: 'true' 
    