on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    linter_job:
        runs-on: ubuntu-latest
        steps:
          # Step 1.
          - name: Checkout code
            uses: actions/checkout@v4

          # Step 2.
          - name: Instalar dependències
            run: npm install --legacy-peer-deps
    
          # Step 4.
          # - name: Linter execution
          #   uses: github/super-linter@v4
          #   env: 
          #     DEFAULT_BRANCH: main
          #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #     LINTER_RULES_PATH: /
          #     JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          #     VALIDATE_JAVASCRIPT_ES: 'true' 
              
    cypress_job:
        runs-on: ubuntu-latest
        needs:
            - linter_job

        steps:
          # Step 1.
          - name: Checkout code
            uses: actions/checkout@v4
          
          # # Step 2.
          # - name: Ajustant nodejs
          #   uses: actions/setup-node@v3
          #   with:
          #     node-version: '18.18.0'
          
          # # Step 3.
          # - name: Install dependencies
          #   run: npm install --legacy-peer-deps

          # # Step 4.
          # - name: Construint el projecte
          #   run: npm run build

          # Step 5.          
          - name: Correr cypress
            uses: cypress-io/github-action@v6
            with:
              start: npm start
              wait-on: "http://localhost:3000"
            id: cypress
            continue-on-error: true

          - name: Guardar resultat
            run: echo "${{ steps.cypress.outcome }}" > result.txt
            continue-on-error: true

          # Step 6
          - name: Creant l´artifact
            uses: actions/upload-artifact@v4
            with:
              name: result.txt
              path: .
            continue-on-error: true
           

          
            
          
    
    