on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    linter_job:
        runs-on: ubuntu-latest
        steps:
          # Step 1.
          - name: Checkout code
            uses: actions/checkout@v4
    
          # Step 2.
          # - name: Linter execution
          #   uses: github/super-linter@v4
          #   env: 
          #     DEFAULT_BRANCH: main
          #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #     LINTER_RULES_PATH: /
          #     JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          #     VALIDATE_JAVASCRIPT_ES: 'true' 
              
    cypress_job:
        runs-on: ubuntu-latest
        needs:
            - linter_job

        steps:
          # Step 1.
          - name: Checkout code
            uses: actions/checkout@v4
          
          # Step 2.
          - name: Ajustant nodejs
            uses: actions/setup-node@v3
            with:
              node-version: '16'
          
          # Step 3.
          - name: Install dependencies
            run: npm install

          # Step 4.
          - name: Construint el projecte
            run: npm run build

          # Step 5.
          - name: Corrent els tests de cypress
            uses: cypress-io/github-action@v6
            # S´asegurem de que continua en cas de que hi haja errors.
            continue-on-error: true

          # Step 6.
          - name: Creant arxiu d´ixida
            run: echo "Results" > result.txt
            continue-on-error: true
          
          # Step 7.
          - name: Pujant artefacte a l´arxiu creat
            uses: actions/upload-artifact@v2
            with:
              name: result_cypress
              path: result.txt
            continue-on-error: true
           

          
            
          
    
    